name: ${COMPOSE_PROJECT_NAME}

services:
  postgres:
    image: ${PG_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: unless-stopped
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  elasticsearch:
    image: ${ES_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-es
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ES_XPACK_SECURITY_ENABLED}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  pg_data:
    name: ${PG_VOLUME_NAME}
  es_data:
    name: ${ES_VOLUME_NAME}
